# Generated by Django 4.0 on 2022-01-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='movie',
        ),
        migrations.DeleteModel(
            name='PaymentIntent',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
