# Generated by Django 4.0 on 2022-01-17 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_paymentintent_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='occupant_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='referrer',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
